name: import_order_lint
description: "A custom lint plugin for enforcing import order in Dart files."
version: 0.0.3
repository: https://github.com/anusii/import-order-lint

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  custom_lint_builder: ^0.7.0
